#!/usr/bin/env node

// Module dependencies.

const app = require("../postgres")
const debug = require("debug")("postgres:server")
const http = require("http")

// Get port from environment and store in Express.

const port = 3006
app.set("port", port)

// Create HTTP server.

const server = http.createServer(app)

// Listen on provided port, on all network interfaces.

server.listen(port)
server.on("listening", onListening)

// Event listener for HTTP server "listening" event.

function onListening() {
	const addr = server.address()
	const bind = typeof addr === "string"
		? "pipe " + addr
		: "port " + addr.port
	debug("Listening on " + bind)
}

process.on("SIGINT", () => {
	console.info("SIGINT signal received")
	server.close( (err) => {
		if (err) {
			console.error(err)
			process.exit(1)
		}
	})
})
